import frappe

def execute():
    if frappe.db.exists("DocType", "Material Coverage Details"):
        return

    frappe.get_doc({
        "doctype": "DocType",
        "name": "Material Coverage Details",
        "module": "Fmg App",
        "istable": 1,
        "editable_grid": 1,
        "fields": [{'fieldname': 'custom_column_break_x54sv',
            'label': '',
            'fieldtype': 'Column Break',
            'options': None,
            'insert_after': 'custom_unit_req_po',
            "in_list_view": 1},
            {'fieldname': 'custom_final_labor_cost',
            'label': 'Final labor cost (₹)',
            'fieldtype': 'Currency',
            'options': None,
            'insert_after': 'custom_rate_per_unit',
            "in_list_view": 1},
            {'fieldname': 'custom_rate_per_unit',
            'label': 'Rate per unit',
            'fieldtype': 'Currency',
            'options': None,
            'insert_after': 'custom_labor_units',
            "in_list_view": 1},
            {'fieldname': 'custom_labor_units',
            'label': 'Labor units',
            'fieldtype': 'Int',
            'options': None,
            'insert_after': 'custom_column_break_x54sv',
            "in_list_view": 1},
            {'fieldname': 'custom_labor_margin_value',
            'label': 'Labor Margin Value',
            'fieldtype': 'Float',
            'options': None,
            'insert_after': 'custom_material_margin_value',
            "in_list_view": 1},
            {'fieldname': 'custom_labor_margin_type',
            'label': 'Labor Margin Type',
            'fieldtype': 'Select',
            'options': 'Percentage\nPer Unit',
            'insert_after': 'custom_material_margin_type',
            "in_list_view": 1},
            {'fieldname': 'custom_material_margin_value',
            'label': 'Material Margin Value',
            'fieldtype': 'Float',
            'options': None,
            'insert_after': 'custom_column_break_4ub7l',
            "in_list_view": 1},
            {'fieldname': 'custom_column_break_4ub7l',
            'label': '',
            'fieldtype': 'Column Break',
            'options': None,
            'insert_after': 'custom_labor_margin_type',
            "in_list_view": 1},
            {'fieldname': 'custom_material_margin_type',
            'label': 'Material Margin Type',
            'fieldtype': 'Select',
            'options': 'Percentage\nPer Unit',
            'insert_after': 'custom_section_break_5ppzo',
            "in_list_view": 1},
            {'fieldname': 'custom_section_break_5ppzo',
            'label': '',
            'fieldtype': 'Section Break',
            'options': None,
            'insert_after': 'custom_final_labor_cost',
            "in_list_view": 1},
            {'fieldname': 'custom_unit_req_po',
            'label': 'Unit Req PO',
            'fieldtype': 'Link',
            'options': 'UOM',
            'insert_after': 'custom_last_item_code',
            "in_list_view": 1},
            {'fieldname': 'custom_floor_thickness',
            'label': 'Floor Thickness (Meter)',
            'fieldtype': 'Float',
            'options': None,
            'insert_after': 'total_cost',
            "in_list_view": 1},
            {'fieldname': 'custom_last_item_code',
            'label': 'Last Item Code',
            'fieldtype': 'Data',
            'options': None,
            'insert_after': 'custom_linked_resource_row',
            "in_list_view": 1},
            {'fieldname': 'custom_linked_resource_row',
            'label': 'Linked Resource Row',
            'fieldtype': 'Data',
            'options': None,
            'insert_after': 'custom_total_material_cost_',
            "in_list_view": 1},
            {'fieldname': 'custom_total_material_cost_',
            'label': 'Total Material Cost (₹)',
            'fieldtype': 'Currency',
            'options': None,
            'insert_after': 'custom_total_qty_needed',
            "in_list_view": 1},
            {'fieldname': 'custom_total_qty_needed',
            'label': 'Total Qty Needed',
            'fieldtype': 'Float',
            'options': None,
            'insert_after': 'parent_prp_row',
            "in_list_view": 1}]
    }).insert(ignore_permissions=True)
